# Generated by Django 2.1.7 on 2019-04-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_proj2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20, null=True)),
                ('place_title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('latitude', models.DecimalField(decimal_places=10, editable=False, max_digits=18, null=True)),
                ('longitude', models.DecimalField(decimal_places=10, editable=False, max_digits=18, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='homebase',
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
    ]
