# Generated by Django 2.1.7 on 2019-05-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_proj2app', '0002_auto_20190403_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.TextField()),
                ('date', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='display_name',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='no password', max_length=30),
            preserve_default=False,
        ),
    ]
