# Generated by Django 2.1.7 on 2019-05-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_proj2app', '0004_auto_20190502_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='hash_id',
            field=models.CharField(max_length=32),
        ),
    ]
