# Generated by Django 2.1.7 on 2019-05-03 15:27

import API_proj2app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_proj2app', '0005_auto_20190503_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=API_proj2app.models.Base64Field(db_column='image'),
        ),
    ]
